### ISSUE TITLE
Book links not working in README.md

### ISSUE THREAD

**Issue by SaiUbc** [UBC-CS/cpsc330-2024W1#5]
Hi!

The following links are not working in the Reference Material of README:

- [An Introduction to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)
- [Data Mining: Practical Machine Learning Tools and Techniques (PMLTT)](https://www.wi.hs-wismar.de/~cleve/vorl/projects/dm/ss13/HierarClustern/Literatur/WittenFrank-DM-3rd.pdf)
- [Artificial Intelligence 2E: Foundations of Computational Agents](https://artint.info/2e/html/ArtInt2e.htm)

It would be great if online pdf links can be attached, thanks! 🙂

**Comment by firasm** [comment]
Thanks for reporting this @SaiUbc !
